# Databricks notebook source
# MAGIC %md
# MAGIC # CDC (Change Data Capture) DLT Pipeline
# MAGIC 
# MAGIC This pipeline handles incremental data changes from source systems:
# MAGIC - Tracks inserts, updates, and deletes
# MAGIC - Maintains slowly changing dimensions (SCD Type 2)
# MAGIC - Supports late-arriving data
# MAGIC 
# MAGIC Generated by Lakebridge Migration Tool

# COMMAND ----------

import dlt
from pyspark.sql import functions as F

# COMMAND ----------

# MAGIC %md
# MAGIC ## Source: CDC Events Stream

# COMMAND ----------

@dlt.table(
    name="cdc_raw_events",
    comment="Raw CDC events from source system",
    table_properties={
        "pipelines.autoOptimize.managed": "true"
    }
)
def cdc_raw_events():
    """Ingest CDC events from source."""
    return (
        spark.readStream
        .format("cloudFiles")
        .option("cloudFiles.format", "json")
        .option("cloudFiles.inferColumnTypes", "true")
        .load("/mnt/cdc/events/")
    )

# COMMAND ----------

# MAGIC %md
# MAGIC ## Apply Changes: SCD Type 1 (Overwrite)

# COMMAND ----------

dlt.create_streaming_table(
    name="target_table_scd1",
    comment="Target table with SCD Type 1 (latest value only)",
    table_properties={
        "pipelines.autoOptimize.managed": "true"
    }
)

dlt.apply_changes(
    target="target_table_scd1",
    source="cdc_raw_events",
    keys=["id"],
    sequence_by="event_timestamp",
    apply_as_deletes=F.expr("operation = 'DELETE'"),
    except_column_list=["operation", "event_timestamp"],
)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Apply Changes: SCD Type 2 (History Tracking)

# COMMAND ----------

dlt.create_streaming_table(
    name="target_table_scd2",
    comment="Target table with SCD Type 2 (full history)",
    table_properties={
        "pipelines.autoOptimize.managed": "true"
    }
)

dlt.apply_changes(
    target="target_table_scd2",
    source="cdc_raw_events",
    keys=["id"],
    sequence_by="event_timestamp",
    apply_as_deletes=F.expr("operation = 'DELETE'"),
    except_column_list=["operation", "event_timestamp"],
    stored_as_scd_type=2,  # Enable SCD Type 2
)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Current View (SCD Type 2)

# COMMAND ----------

@dlt.view(
    name="current_records",
    comment="Current (non-deleted) records from SCD Type 2 table"
)
def current_records():
    """Get only current records from SCD Type 2 table."""
    return (
        dlt.read("target_table_scd2")
        .filter("__END_AT IS NULL")
    )
